version: '3.8'

services:
  app:
    image: ${GITHUB_USERNAME}/dreamquest-test-app:${TAG:-latest}
    container_name: dreamquest-test-app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - app-logs:/logs
    networks:
      - dq-app-network
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: dreamquest-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    networks:
      - dq-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  dq-app-network:
    driver: bridge

volumes:
  pgdata:
    external: true
    name: dreamquest-pgdata
  app-logs:
    external: true
    name: dreamquest-app-logs
  postgres-logs:
    external: true
    name: dreamquest-postgres-logs
