name: Production Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Verify secrets exist
      run: |
        echo "Checking Docker Hub credentials..."
        if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
          echo "::error::DOCKERHUB_USERNAME is empty!"
          exit 1
        fi
        if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "::error::DOCKERHUB_TOKEN is empty!"
          exit 1
        fi
        echo "Credentials verified successfully"
        
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Docker Hub Login
      run: |
        echo "Logging into Docker Hub..."
        docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" docker.io
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          dreamquest/dreamquest-test-app:latest
          dreamquest/dreamquest-test-app:${{ github.sha }}
          
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y jq
      
    - name: Deploy to Portainer
      run: |
        # Read and escape compose file
        COMPOSE_CONTENT=$(jq -Rs . < docker-compose.prod.yml)
        
        # Create payload with proper JSON escaping
        PAYLOAD=$(jq -n \
          --arg name "dreamquest-test" \
          --arg stackFileContent "$COMPOSE_CONTENT" \
          --arg tag "${{ github.sha }}" \
          --arg db_name "${{ secrets.DB_NAME }}" \
          --arg db_user "${{ secrets.DB_USER }}" \
          --arg db_password "${{ secrets.DB_PASSWORD }}" \
          '{
            "name": $name,
            "stackFileContent": $stackFileContent,
            "env": [
              {"name": "TAG", "value": $tag},
              {"name": "DB_HOST", "value": "postgres"},
              {"name": "DB_NAME", "value": $db_name},
              {"name": "DB_USER", "value": $db_user},
              {"name": "DB_PASSWORD", "value": $db_password}
            ],
            "prune": true,
            "pullImage": true
          }')
        
        # Create/update stack
        curl -X POST "${{ secrets.PORTAINER_URL }}/api/stacks?method=repository&type=2&endpointId=${{ secrets.PORTAINER_ENDPOINT_ID }}" \
          -H "X-API-Key: ${{ secrets.PORTAINER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD"
