name: Production Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/dreamquest-test-app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/dreamquest-test-app:${{ github.sha }}
          
    - name: Deploy to Portainer
      uses: portainer/deploy-to-portainer-action@v1
      with:
        portainer_host: 'https://portainer.dreamquest.vip'
        portainer_api_key: ${{ secrets.PORTAINER_API_KEY }}
        endpoint_id: ${{ secrets.PORTAINER_ENDPOINT_ID }}
        stack_name: 'dreamquest-test'
        stack_file: 'docker-compose.prod.yml'
        env_variables: |
          TAG=${{ github.sha }}
          DB_HOST=postgres
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        prune: true
        pull_image: true
